name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0
    environment: UPTOBOX
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Create MockFileConfig
      run: | 
        cp ./UptoboxApi/Utils/FileConfig/MockFileConfig.cs.example ./UptoboxApi/Utils/FileConfig/MockFileConfig.cs
        sed -i 's/myToken/${{secrets.TOKEN}}/' ./UptoboxApi/Utils/FileConfig/MockFileConfig.cs
    - name: Build & Test Project
      run: dotnet test ./UptoboxApi.Test/UptoboxApi.Test.csproj --verbosity normal
