name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./UptoboxApi/UptoboxApi.csproj
    - name: Build
      run: dotnet build ./UptoboxApi/UptoboxApi.csproj --no-restore
    - name: Build Test
      run: dotnet build ./UptoboxApi.Test/UptoboxApi.Test.csproj --no-restore
    - name: Test
      run: dotnet test ./UptoboxApi.Test/UptoboxApi.Test.csproj --no-build --verbosity normal
