name: Testing

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    container: mcr.microsoft.com/dotnet/sdk:5.0
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./UptoboxApi/UptoboxApi.csproj
    - name: Test
      run: dotnet test ./UptoboxApi.Test/UptoboxApi.Test.csproj --no-build
      env:
        POSTGRES_HOST: postgres
        POSTGRES_USERNAME: postgres
        POSTGRES_PASSWORD: postgres
